spring.application.name=backend

# THE CONFIGURATION FOR THE CLOUD
# We use ${VARIABLE_NAME} so IBM can inject the real values later.
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# This will grab the username from IBM settings
spring.datasource.username=${DB_USER}

# This will grab the password from IBM settings
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keep this as 'update' so it doesn't delete your tables
spring.jpa.hibernate.ddl-auto=update